# Intro to NumPy: my own experimentation

In [3]:
import numpy as np

In [4]:
x = np.array([1, 2, 3, 4, 5])

In [5]:
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>
int32


In [6]:
y = np.array([ [1,2,3], [4,5,6], [7,8,9] ])

In [7]:
print(y)
print(y.shape)
print(type(y))
print(y.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
<class 'numpy.ndarray'>
int32


In [8]:
np.ones((6,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
np.ones((6,9), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros((2,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
np.full((4,6), 7)

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

# - Matrix

A **matrix** is a **2** dimensional array, with size = row x column.

## Example
> `np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )`

# - Identity matrix (famous in linear algebra)

## Definition
> An identity matrix is a square-shaped 2-dimensional matrix, with only 1s along its main diagonal and 0s everywhere else.

### Below, see an example of identity matrix: a 5x5 identity matrix


In [13]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# - Diagonal Matrix

## Definition
> Square-shaped 2-dimensional matrix with numbers along its main diagonal and 0s everywhere else.

### Below, see an example of a 5x5 (2D) diagonal matrix

In [14]:
D = np.diag( [10, 20, 30, 40, 50] )
print(D)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


# - Numpy's arange()

> Arguments
`np.arange(start, stop, step)`

## Note: 
- stop is exclusive.

- you can specify 1 argument (will be the stop arg, with default start = 0, default step = 1)
- you can specify 2 arguments (will be start and stop, with default step = 1)
- you can specify all 3 arguments. 


In [15]:
c = np.arange(1, 10, 2)
print(c)

[1 3 5 7 9]


In [16]:
d = np.arange(2, 19)
print(d)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [17]:
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


# - np.linspace()

> Arguments
`np.linspace(start, stop, n)`

# n
> n is the number of evenly spaced numbers wanted in the range from start to end 
>> NOT EQUAL TO THE STEP, step is the distance between 2 consecutive numbers e.g. in np.arange()

## Note:

- start AND stop are inclusive, *unlike np.arange() where stop was exclusive*.

- requires AT LEAST **2** arguments, *unlike np.arange() where one was enough*.

- if not specified, n = 50


In [18]:
z = np.linspace(0, 25, 10)  # we want 10 evenly spaced numbers in the range of 0 (inclusive) to 25 (inclusive!!)
print(z)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


## Additional argument to np.linspace()

If you set the argument `endpoint = False` in np.linespace, the end is **excluded**

### Below, see an example

In [19]:
u = np.linspace(0, 25, 10, endpoint=False)
print(u)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


> Above, we have the 10 evenly spaced numbers in the range from 0 (inclusive) to 25 (**exclusive**).

> Because the range is now from 0 to 24 inclusive, the spacing between the values changed.

# - np.reshape()

In [20]:
x = np.arange(0, 20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


**Above**, we have a 1D array of shape (20,)

In [21]:
x = np.reshape(x, (4,5))   # the new shape must be compatible with the number of elements in x (= 20)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


**NOW, above**, we have a 2D array of shape (4,5)

> other shapes of 2D arrays compatible with a 1D 20-elements array:

- (5,4)
- (2,10)
- (10,2)

# - NumPy Array Methods


In [22]:
x = np.arange(20).reshape((4,5))  # same result as above
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [23]:
y = np.linspace(0, 20, 12).reshape((4,3))
print(y)

[[ 0.          1.81818182  3.63636364]
 [ 5.45454545  7.27272727  9.09090909]
 [10.90909091 12.72727273 14.54545455]
 [16.36363636 18.18181818 20.        ]]


# - NumPy arrays containing RANDOM numbers

## Example below: the random function from the random module of NumPy
>  argument = shape of the array

> array of precised shape contains random numbers between 0 (inclusive) and 1 (exclusive).

In [24]:
x = np.random.random((3,3))
print(x)

[[0.32502357 0.75497644 0.26634176]
 [0.21300741 0.45726526 0.72086967]
 [0.34971756 0.87816949 0.338705  ]]


## Example below: the randint function from the random module of NumPy
> arguments: lower bound (inclusive), upper bound (exclusive), shape

> array of precised shape contains random numbers in the specified range.

In [25]:
y = np.random.randint(0, 20, (6,5))
print(y)

[[ 4  1 12  9  8]
 [11 18 13  4  9]
 [18 18 14  9 12]
 [12  1  3 15 16]
 [19  9 17  5 18]
 [ 8  2  0 19  4]]


## Example: random numbers drawn from proba distributions

## example below: np.random.normal()

> arguments: mean, sd, size

In [26]:
x = np.random.normal(0, 0.1, size = (10,10))
print(x)

[[ 5.42447575e-03  9.92527346e-02 -1.04935498e-02 -4.66713255e-02
   1.36256217e-01 -3.10660305e-02  9.44022009e-02  1.60550345e-02
   5.64860314e-02 -1.25951291e-02]
 [ 1.94394556e-01  9.18821776e-02 -3.18465140e-02 -1.83768174e-02
   6.07484409e-02 -2.16470869e-02  1.44620582e-01  6.69905771e-02
  -1.18089578e-01 -1.86186785e-01]
 [ 2.45528225e-01  5.94936757e-02 -1.04548557e-01  5.41436647e-02
   1.27153428e-01  7.11930713e-02 -2.56584346e-01 -3.84623582e-02
  -6.23042012e-02 -1.01207337e-01]
 [ 1.21275307e-01  4.41673805e-02  1.11250636e-01 -1.66765354e-03
  -1.43152911e-02  9.02392986e-02 -8.53770621e-02 -3.35955114e-02
  -4.67999445e-02  6.44384917e-02]
 [-1.50735902e-01 -1.18386329e-01  7.49684909e-02  4.12047712e-03
   5.89485411e-02 -9.45589534e-02  2.13384978e-01 -8.55002708e-02
  -3.67202817e-02  1.32597528e-01]
 [-2.85895931e-02  7.61686910e-02  1.76872714e-01  1.71173895e-02
   4.18512364e-02  3.42794082e-02  1.03450759e-01  1.25912252e-01
  -7.08352304e-03  1.76116391e-01

In [27]:
print(x.mean())  # very close to 0, argument passed to np.random.normal() above
print(x.std())   # very close to 0.1, argument passed to np.random.normal() above
print(x.max())
print(x.min())  # min and max are approx. symmetrical about mean of x, so that also satisfies another statistical property.

0.014412472017236617
0.09404966757454236
0.24552822465122862
-0.2565843458885939


# - Idexing, accesing, changing elements in ndarrays

In [28]:
x = np.array( [1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [29]:
print(x[3]) # accessing x's FOURTH element (ndarrays have 0-indexing, like lists in plain python)

4


**Note: ndarrays are MUTABLE.**
> See below:

In [30]:
x[2] = 31 # changing x's THIRD element from 3 to 31
print(x)

[ 1  2 31  4  5]


In [31]:
y = np.linspace(2, 20, 10, dtype=int).reshape((5,2))
print(y)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [32]:
print(y[(2, 1)])  # accessing the element in the 3rd row and 2nd column = 12

12


In [33]:
y[(2,1)] = 34    # changing the value of the element in the 3rd row and 2nd column, from 12 TO 34
print(y)

[[ 2  4]
 [ 6  8]
 [10 34]
 [14 16]
 [18 20]]


# - Delete elements from ndarrays

## for rank 2 arrays:

**additional argument** to specify: **axis**
> axis = 0 for selecting rows 
> axis = 1 for selecting columns

In [34]:
x = np.array( [1,2,3,4,5] )
print(x)

[1 2 3 4 5]


In [35]:
x = np.delete(x, [0, 4])  # deleting the FIRST and the FIFTH/LAST elements of x
print(x)

[2 3 4]


In [36]:
Y = np.arange(1,10).reshape((3,3))
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
W = np.delete(Y, 0, axis=0)  # deleting FIRST ROW of Y
print(W)

[[4 5 6]
 [7 8 9]]


In [38]:
V = np.delete(Y, 1, axis=1)  # deleting the SECOND COLUMN of Y
print(V)

[[1 3]
 [4 6]
 [7 9]]


In [39]:
B = np.delete(Y, [0,1], axis=1)  # deleting the first AND second COLUMNS of Y
print(B)

[[3]
 [6]
 [9]]


# - Add values to ndarrays

## The append function

### in rank 1 arrays:

In [40]:
x = np.array( [1,2,3,4,5] )
print(x)

[1 2 3 4 5]


In [41]:
x = np.append(x, 6)  # appending 6 to rank 1 array x
print(x)

[1 2 3 4 5 6]


In [42]:
x = np.append(x, [7,8])  # appending 7 AND 8 to rank 1 array x, using a list [7,8]
print(x)

[1 2 3 4 5 6 7 8]


### in rank 2 arrays:

In [43]:
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
y = np.append(y, [ [10, 11, 12] ], axis=0)   # appending [10 11 12], new row, to rank 2 array y (along the axis of rows, 0)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
y = np.append(y, [ [-1], [-2], [-3], [-4] ], axis=1)  # appending a new column to rank 2 array y (along the axis of columns, 1)
print(y)

[[ 1  2  3 -1]
 [ 4  5  6 -2]
 [ 7  8  9 -3]
 [10 11 12 -4]]


# - Insert values to ndarrays (in between other values, not to the end)

## in rank 1 arrays:

In [46]:
x = np.array( [1, 2, 5, 6] )
print(x)

[1 2 5 6]


In [47]:
x = np.insert(x, 2, [3,4])  # inserting 3 and 4, with starting index = 2 
print(x)

[1 2 3 4 5 6]


## in rank 2 arrays: (inserting an entire row or column)

In [48]:
y = np.array( [ [1,2,3], [7,8,9] ] )
print(y)

[[1 2 3]
 [7 8 9]]


In [49]:
y = np.insert(y, 1, [ [4,5,6] ], axis=0)  # inserting a new row as the second row (index = 1)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
y = np.insert(y, 2, 5, axis=1)  # inserts a new colum full of 5, as the third column of the rank 2 4x3 array y
print(y)

[[1 2 5 3]
 [4 5 5 6]
 [7 8 5 9]]


# - Stack NumPy arrays

**condition: the shape of the arrays we want to stack MUST be IDENTICAL.**

## On top of each other (vertical stacking):

In [51]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

I = np.vstack((a,b))
print(I)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [52]:
c = np.array([2,7,8])

d = np.arange(0,6).reshape(2,3)

J = np.vstack((c,d))
print(J)

[[2 7 8]
 [0 1 2]
 [3 4 5]]


## Side by side (horizontal stacking):

In [53]:
M = np.hstack((a,b))
print(M)

[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
e = np.arange(0,9).reshape(3,3)

f = np.arange(10, 19).reshape(3,3)

N = np.hstack((e,f))
print(N)

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


# - Slicing ndarrays

> Access subsets of NumPy arrays with **slicing**, instead of accessing one element at a time.

> 3 ways of slicing:

|ndarray[start:end]  | specified start and specified end indexes                                        |
|--------------------|----------------------------------------------------------------------------------|                      |ndarray[start:]     | no specified end, so default end = the index of the last value of the array      |
|--------------------|----------------------------------------------------------------------------------|                       | ndarray[:end]      | no specified start, so default start = the index of the first value of the array |

> ending index is always exclusive.
          

In [55]:
x = np.arange(1, 21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [56]:
z = x[2:, 1:4]     # x[rows, columns]
print(z)

[[12 13 14]
 [17 18 19]]


In [57]:
w = x[1, :]   # selects the entire second row of x
print(w)

[ 6  7  8  9 10]


# IMPORTANT:

## - z and w are now "views of x": they aren't new variables that store one part of x.
## - SO making changes to w or z will ALSO change the corresponding parts in x !

In [58]:
# see what z is above

z[1, 1] = 529  # changing 18 to 529 in z
print(z, '\n')

print(x, '\n')

[[ 12  13  14]
 [ 17 529  19]] 

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17 529  19  20]] 



## Above:

you can see that the change in z also occured in x.

## > Creating NEW arrays (not views) that are slices of another array
### Using NumPy's copy function/method

In [59]:
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [60]:
z = np.copy(x[2:, 1:4])   # using NumPy's copy function: can also write z = x[2:, 1:4].copy() -> AS A METHOD
print(z)

[[12 13 14]
 [17 18 19]]


In [61]:
z[1, 2] = 281
print(z, '\n')

print(x, '\n')  # x IS NOT AFFECTED BY THE CHANGE IN Z NOW

[[ 12  13  14]
 [ 17  18 281]] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 



> Using np.copy(), we have created an array 'z' completely independent of x.

# - Extracting values along the main diagonal of an ndarray

In [62]:
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [63]:
z = np.copy(np.diag(x))   # extracts diagonal values of array x, z being a new array independent of x
print(z)

[ 1  7 13 19]


# - Extracting values ABOVE the main diagonal of an ndarray

print(x, '\n')
print('Diagonal of x is:', np.diag(x), '\n')

j = np.diag(x, k = 1)   # by default, k = 0 : np.diag(x) = np.diag(x, k=0) and gives back the main diagonal of x
print(j, '\n')

# - Extracting the values BELOW the main diagonal of an ndarray

In [64]:
print(x, '\n')
print('Diagonal of x is:', np.diag(x), '\n')

f = np.diag(x, k = -1)   # by default, k = 0 : np.diag(x) = np.diag(x, k=0) and gives back the main diagonal of x
print(f, '\n')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

Diagonal of x is: [ 1  7 13 19] 

[ 6 12 18] 



# - Extracting the unique elements in an ndarray

> Using NumPy's unique function

In [65]:
x = np.array( [ [1,2,3], [3,2,9], [2,7,9] ] )
print(x)

[[1 2 3]
 [3 2 9]
 [2 7 9]]


In [66]:
print(np.unique(x))   # prints the unique values of the rank 2 3x3 array x

[1 2 3 7 9]


# - Boolean Indexing

## Why:
> for selecting elements in an array using logical arguments (if element satisfies a condition) instead of explicit indices.
> useful when we don't know the indices of the elements we want (e.g. in 1000x1000 arrays) and we want a specific subset of elements that satisfy a specific condition (e.g. elements larger than 10)


In [67]:
x = np.arange(0,25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Select elements greater than 10:

In [68]:
print(x[x > 10])   # instead of indices, using a boolean expression for selecting a specific subset of elements in array x

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


Other example:

In [69]:
print(x[(x > 10) & (x < 17)])  # don't write 'and' + keep () in both sides of & : to make the code work as expected

[11 12 13 14 15 16]


Changing the values of a specific subset of elements of the array x using boolean indexing:

In [70]:
x[x > 7] = -15
print(x)

[[  0   1   2   3   4]
 [  5   6   7 -15 -15]
 [-15 -15 -15 -15 -15]
 [-15 -15 -15 -15 -15]
 [-15 -15 -15 -15 -15]]


# - Set operations

## Create arrays for the intersection, difference and union of two RANK 1 arrays

In [71]:
x = np.array([2,1,6,8,9])
y = np.array([6,5,9,8,3])

print(np.intersect1d(x, y), '\n') # intersection of x and y
print(np.setdiff1d(x, y), '\n')   # difference of x and y: (x,y) so returns the values IN x that are not in y, not viceversa
print(np.union1d(x, y), '\n')    # union of x and y

[6 8 9] 

[1 2] 

[1 2 3 5 6 8 9] 



# - Sorting NumPy's arrays

## Using sort function and sort method:
> **DIFFERENCE IN HOW THE DATA IS STORED IN MEMORY**

**sort used as a function:**

In [72]:
x = np.array([2,1,6,6,8,9])

print(np.sort(x))  # will sort x OUT OF PLACE (and keep repeated values) and leave the original array x as is

print('no change to original array x:', x, '\n')  # original x array did not change

[1 2 6 6 8 9]
no change to original array x: [2 1 6 6 8 9] 



In [73]:
print(np.sort(np.unique(x)))  # to sort the unique elements of x out of place

[1 2 6 8 9]


**sort used as a method:**

In [74]:
x.sort()

print('original x has been changed:', x, '\n')

original x has been changed: [1 2 6 6 8 9] 



**Sorting rank 2 arrays:**

In [75]:
y = np.array( [ [1,2,4,9,6], [9,8,5,8,0], [6,8,3,8,0] ] )

print(y)

[[1 2 4 9 6]
 [9 8 5 8 0]
 [6 8 3 8 0]]


- Sorting rank 2 array by row (axis=0):

In [76]:
print(np.sort(y, axis = 0))

[[1 2 3 8 0]
 [6 8 4 8 0]
 [9 8 5 9 6]]


- Sorting rank 2 array by column (axis=1):

In [77]:
print(np.sort(y, axis = 1))

[[1 2 4 6 9]
 [0 5 8 8 9]
 [0 3 6 8 8]]


# - Arithmetic operations on ndarrays

> NumPy allows element-wise operations AND matrix operations.

## Here, we'll only look at ELEMENT-WISE operations on arrays

**- THE *element-wise* ADDITION OF TWO ARRAYS:**

In [78]:
x = np.array([1,5,8,9,6])
y = np.array([2,8,5,4,7])

print(x + y)
# OR
print(np.add(x, y), '\n')

[ 3 13 13 13 13]
[ 3 13 13 13 13] 



**- THE *element-wise* SUBTRACTION OF TWO ARRAYS:**

In [79]:
print(x - y)
# OR
print(np.subtract(x,y), '\n')

[-1 -3  3  5 -1]
[-1 -3  3  5 -1] 



**- THE *element-wise* MULTIPLICATION OF TWO ARRAYS:**

In [80]:
print(x * y)
#OR
print(np.multiply(x,y), '\n')

[ 2 40 40 36 42]
[ 2 40 40 36 42] 



**- THE *element-wise* DIVISION OF TWO ARRAYS:**

In [81]:
print(x / y)
#OR
print(np.divide(x,y), '\n')

[0.5        0.625      1.6        2.25       0.85714286]
[0.5        0.625      1.6        2.25       0.85714286] 



# - Broadcasting
> how NumPy handles element-wise arithmetic operations with **arrays of DIFFERENT shapes**

> In element-wise arithmetic operations, the arrays operated on MUST have the SAME shape OR be BROADCASTABLE.

# - Mathematical functions on arrays

In [86]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [87]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [88]:
print(np.exp(x))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [89]:
print(np.power(x, 2))

[ 1  4  9 16 25]


# - Statistical functions on arrays
> Provide statistical info about the elements in an array (e.g. mean, sd)

In [91]:
x = np.array([1,2,3,4]).reshape(2,2)
print(x)

[[1 2]
 [3 4]]


In [93]:
print('average of all:', x.mean())

average of all: 2.5


In [101]:
print('averages of rows:', x.mean(axis=1))

averages of rows: [1.5 3.5]


In [102]:
print('averages of columns:', x.mean(axis=0))

averages of columns: [2. 3.]


In [103]:
print('sum of all:', x.sum())

sum of all: 10


In [104]:
print('sum of columns:', x.sum(axis=0))

sum of columns: [4 6]


In [105]:
print('sum of rows:', x.sum(axis=1))

sum of rows: [3 7]


In [106]:
print(x.std())

1.118033988749895


In [108]:
print(np.median(x))

2.5


In [109]:
print(x.min())

1


In [110]:
print(x.max())

4


# - Adding a number to each element of an array

In [120]:
print(x, '\n')

print(x + 3)

[[1 2]
 [3 4]] 

[[4 5]
 [6 7]]


# - Subtracting a number from each element of an array

In [119]:
print(x, '\n')

print(x - 3)

[[1 2]
 [3 4]] 

[[-2 -1]
 [ 0  1]]


# - Multiply by a number each element of an array

In [118]:
print(x, '\n')

print(x * 3)

[[1 2]
 [3 4]] 

[[ 3  6]
 [ 9 12]]


# - Divide by a number each element of an array

In [117]:
print(x, '\n')

print(x / 3)

[[1 2]
 [3 4]] 

[[0.33333333 0.66666667]
 [1.         1.33333333]]


# Note on broadcasting:

> **NumPy is working behind the scene to BROADCAST the number 3 along the rank 2 2x2 array x
SO THAT they have the *same* shape.**

**Note: Subject to certain constraints, NumPy can do the same for two arrays of *different* shapes.**

In [125]:
x = np.arange(9).reshape(3,3)
y = np.array([1,2,3])

print(x, '\n')
print(y, '\n')

print('x + y =') 
print(x + y)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[1 2 3] 

x + y =
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


Above, we can see that 1 (from y) is added to every elements in the first column of x, 2 (from y) is added to every elements in the second column of x, and 3 (from y) is added to every elements in the third column of x.

**NumPy is able to add a 1x3 array (y) to a 3x3 array (x) by broadcasting the smaller array (y) along the bigger array (x).**
> NumPy can do this, provided that the smaller array CAN be extended to fit the shape of the bigger array.

- See documentation of NumPy for more info on **broadcasting** and its rules.